#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <math.h>
#include "../../lib/picomms.h"
#include "../../lib/common.h"
#include "maze.h"

extern robot_state_t robot;
extern coords_grid_t path[16];

/** 
 * Follow the path generated by Lee to the finish line
 */
void follow_path() {
    while(robot.path_array_length >= 0) {   
        int x_current = robot.grid_pos.x - path[robot.path_array_length].x;
        int y_current = robot.grid_pos.y - path[robot.path_array_length].y;

        if(x_current < 0 && y_current == 0)
            move_fast(1);
        if(x_current > 0 && y_current == 0)
            move_fast(3);
        if(y_current < 0 && x_current == 0)
            move_fast(0);
        if(y_current > 0 && x_current == 0)
            move_fast(2);
        robot.path_array_length--;
    }
}